# 
# V O X E L I Z E D  M A T R I X   H O F F M A N   B R A I N   P H A N T O M


/gate/world/daughters/name phantom
/gate/world/daughters/insert ImageRegularParametrisedVolume
/gate/phantom/geometry/SetImage header_phantomD.h33
/gate/phantom/geometry/setRangeToMaterialFile range_material_phantomD.dat

/gate/phantom/placement/setTranslation  0. 0. 0. mm
/gate/phantom/placement/setRotationAxis 1 0 0
/gate/phantom/placement/setRotationAngle 0 deg
/gate/phantom/attachPhantomSD

#/gate/phantom/setSkipEqualMaterials                      0
#/gate/phantom/setFictitiousEnergy                       111. keV
#/gate/phantom/setGammaDiscardEnergy                     0.1 keV

